
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER E5-471
 */
public class NewJFrame extends javax.swing.JFrame {
String temp = "";
Double ti, bt, h1;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        saran = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tinggi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        berat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jBkeluar = new javax.swing.JButton();
        jBhitung = new javax.swing.JButton();
        jBcoba = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ideal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 210, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 60, 60, 20);
        getContentPane().add(saran);
        saran.setBounds(70, 440, 400, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 60, 20);
        getContentPane().add(tinggi);
        tinggi.setBounds(170, 100, 50, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Hasil diagnosa kesehatan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 370, 240, 30);
        getContentPane().add(berat);
        berat.setBounds(170, 150, 50, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Berat Badan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 160, 90, 20);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Laki-laki");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(270, 210, 100, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Perempuan");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(170, 210, 100, 23);

        jBkeluar.setText("Keluar");
        jBkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(jBkeluar);
        jBkeluar.setBounds(310, 260, 90, 40);

        jBhitung.setText("Hitung");
        jBhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBhitungActionPerformed(evt);
            }
        });
        getContentPane().add(jBhitung);
        jBhitung.setBounds(80, 260, 90, 40);

        jBcoba.setText("Coba Lagi");
        jBcoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcobaActionPerformed(evt);
            }
        });
        getContentPane().add(jBcoba);
        jBcoba.setBounds(200, 260, 90, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 210, 90, 30);
        getContentPane().add(ideal);
        ideal.setBounds(270, 320, 60, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Berat badan anda sekarang adalah");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 320, 240, 30);
        getContentPane().add(nama);
        nama.setBounds(170, 50, 190, 40);
        getContentPane().add(hasil);
        hasil.setBounds(70, 400, 400, 30);

        setBounds(0, 0, 597, 559);
    }// </editor-fold>//GEN-END:initComponents

    private void jBhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBhitungActionPerformed
        // TODO add your handling code here:
        if (nama.getText().equals("")|| berat.getText().equals("")|| tinggi.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kotak Isian Harus Diisi Semua");
        
        }else if(jRadioButton1.isSelected()|| jRadioButton2.isSelected()){
            try{
                Proses();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Masukan ada yang salah");
        }
        
        }else {
            JOptionPane.showMessageDialog(null, "Radio Button Harus Dipilih");
        }
    }//GEN-LAST:event_jBhitungActionPerformed

    private void jBcobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcobaActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        tinggi.setText("");
        berat.setText("");
        ideal.setText("");
        hasil.setText("");
        saran.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jBcobaActionPerformed

    private void jBkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBkeluarActionPerformed
        // TODO add your handling code here:
dispose();
    }//GEN-LAST:event_jBkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField berat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField ideal;
    private javax.swing.JButton jBcoba;
    private javax.swing.JButton jBhitung;
    private javax.swing.JButton jBkeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.parseDouble(tinggi.getText());
        bt = Double.parseDouble(berat.getText());
        
        
        if (jRadioButton1.isSelected()){
            h1 = (ti - 100)* 1;
        } else if (jRadioButton2.isSelected()){
            h1 = (ti - 104)*1;
        }
        temp = Double.toString(h1.intValue());
        
        if (h1< bt) {
            ideal.setText(temp);
            hasil.setText("Maaf " + nama.getText()+ " , Sepertinya Ada Overweight");
            saran.setText("Banyaklah Berolahraga dan Hindari Makanan Berkolestrool");
        } else if (h1< bt) {
            ideal.setText(temp);
            hasil.setText("Maaf " + nama.getText()+ " , Sepertinya Ada Underweight");
            saran.setText("Banyaklah Mengkonsumsi Makanan yang Berkarbohidrat");
        } else {
            ideal.setText(temp);
            hasil.setText("Maaf " + nama.getText()+ " , Berat Badan Anda Sudah Ideal");
            saran.setText("Lanjutkan Pola Makan Teratur dan Gaya Hidup Sehat :) ");
        }
        
        
    }
}
